name: pixelhouse
favicon: null
layout_spectrum: 0.825025447877124
typography_spectrum: 0.5110620635095984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5984986629337072
  lightness: 0.45046879164874554
  saturation: 0.3258286153431982
  rhythmicContrast: 0.8513319732155651
purpose: []
